# Generated by Django 5.0.3 on 2024-03-11 11:28

import booking.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(validators=[booking.validators.is_date_expired], verbose_name='Start')),
                ('end', models.DateTimeField(validators=[booking.validators.is_date_expired], verbose_name='End')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Count')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Epoch',
                'verbose_name_plural': 'Epochs',
                'ordering': ('start', 'end', 'count', 'status', 'id'),
                'permissions': [('is_operator', 'Is user an operator?')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.epoch', verbose_name='Epoch')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('id',),
                'permissions': [('is_operator', 'Is user an operator?')],
            },
        ),
        migrations.AddField(
            model_name='epoch',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.service', verbose_name='Service'),
        ),
    ]
